name: Daily POST Request

# Trigger on a schedule (daily at midnight UTC) and also allow manual dispatch.
on:
  schedule:
    - cron: '43 06 * * *'
  workflow_dispatch:

jobs:
  trigger_post:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to /run endpoint
        run: curl -X POST https://pzk-data.onrender.com/run
