name: Daily POST Request

on:
  schedule:
    - cron: '10 6 * * *'  # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  trigger_post:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Send POST request with heartbeat
        run: |
          (while true; do echo "Heartbeat: $(date)"; sleep 60; done) &
          curl --max-time 1800 -X POST https://pzk-data.onrender.com/run
