name: Daily POST Request with Heartbeat

on:
  schedule:
    - cron: '10 20 * * *'   
  workflow_dispatch:

jobs:
  trigger_post:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run POST request with heartbeat
        run: |
          echo "Starting heartbeat..."
          # Use stdbuf to force line-buffered output so the heartbeat appears in logs
          stdbuf -oL bash -c "while true; do echo \"Heartbeat: $(date)\"; sleep 60; done" &
          HEART_PID=$!
          echo "Running curl..."
          # Run curl with verbose output and a max time of 1800 seconds (30 minutes)
          curl --verbose --max-time 1800 -X POST https://pzk-data.onrender.com/run
          echo "Curl finished, killing heartbeat"
          kill $HEART_PID || true
