name: Daily POST Request
 
on:
  schedule:
    - cron: '30 05 * * *'
  workflow_dispatch:

jobs:
  trigger_post:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Send POST request to /run endpoint
        run: curl -X POST https://pzk-data.onrender.com/run
